[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dendro"
version = "1.2.0"
description = "A modern package manager and visual dependency inspector for Fedora Linux."
readme = "README.md"
authors = [
    { name = "Yashar", email = "yashar@duck.com" }
]
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.10"
dependencies = [
    "PyQt6>=6.6.0",
]

[project.gui-scripts]
dendro = "main:main"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "ui*"]
